apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: pract8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: icnsat/config-service:v1
#          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: pract8
spec:
  selector:
    app: config-service
  ports:
    - port: 8888
      targetPort: 8888
  type: ClusterIP
