apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: pract8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: icnsat/discovery-service:v2
#          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: pract8
spec:
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
