apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: pract8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: icnsat/order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9003
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: pract8
spec:
  selector:
    app: order-service
  ports:
    - port: 9003
      targetPort: 9003
  type: ClusterIP
