apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-order
  namespace: pract8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-order
  namespace: pract8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: order_RKSP_8_PRACT
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-order
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: pract8
spec:
  selector:
    app: postgres-order
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
