apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-product
  namespace: pract8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product
  namespace: pract8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: product_RKSP_8_PRACT
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-product-storage
      volumes:
        - name: postgres-product-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-product
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product
  namespace: pract8
spec:
  selector:
    app: postgres-product
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
