apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: pract8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: icnsat/product-service:v3
#          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: pract8
spec:
  selector:
    app: product-service
  ports:
    - port: 9002
      targetPort: 9002
  type: ClusterIP
