apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: pract8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: icnsat/user-service:v1
#          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: pract8
spec:
  selector:
    app: user-service
  ports:
    - port: 9001
      targetPort: 9001
  type: ClusterIP
